// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhgjyuwnforkuskplebv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloZ2p5dXduZm9ya3Vza3BsZWJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDAyNTksImV4cCI6MjA1NzE3NjI1OX0.juMDTicqz-3d4GPHzdiLR2GWsRKQzteOXHDYRTGSIsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);